### ISSUE TITLE
Problem with metaClass object when using norm in Groovy

### ISSUE THREAD

**Issue by jeancarlozapata** [dieselpoint/norm#10]
First of all, great library. Small, easy to understand and use. Thanks for working on it.

I'm trying to run the next Groovy script using ```norm``` (note that I've ran successfully the "same" code on a Java project):

```groovy
@GrabConfig(systemClassLoader=true)
@Grab(group='mysql', module='mysql-connector-java', version='5.1.37')
@Grab('org.eclipse.persistence:javax.persistence:2.1.0')
@Grab('com.dieselpoint:norm:0.8.1-rc2')
  
import com.dieselpoint.norm.Database;
import com.dieselpoint.norm.Query;
import com.dieselpoint.norm.sqlmakers.MySqlMaker;

import java.util.List;
import javax.persistence.*;

@Table(name="data")
class Data {
  @Id
  @GeneratedValue
  long id;
  String name;
  long value;

  public Data() {
    this.id = 0;
    this.name = "";
    this.value = 0;
  }
}

System.setProperty("norm.dataSourceClassName", "com.mysql.jdbc.jdbc2.optional.MysqlDataSource");
System.setProperty("norm.serverName", "localhost");
System.setProperty("norm.databaseName", "mytablename");
System.setProperty("norm.user", "root");
System.setProperty("norm.password", "s0meD1ficultPassw0rd");

Database db = new Database();
db.setSqlMaker(new MySqlMaker());

List<Data> data = db.where("name=?", "SayMyName").results(Data.class);
for(Data p : data) {
  System.out.println(p.id + ": " + p.name + " => " + p.value);
  System.out.println("****");
}
```
When I try to run it from the command line, the next error occurs:

```
Caught: com.dieselpoint.norm.DbException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'metaClass' in 'field list'
com.dieselpoint.norm.DbException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'metaClass' in 'field list'
        at com.dieselpoint.norm.Query.results(Query.java:215)
        at com.dieselpoint.norm.Query$results.call(Unknown Source)
        at test-norm-groovy-error.run(test-norm-groovy-error.groovy:37)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'metaClass' in 'field list'
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
        at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:52)
        at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeQuery(HikariPreparedStatementProxy.java)
        at com.dieselpoint.norm.Query.results(Query.java:186)
        ... 2 more
```

This is due to Groovy's ```metaclass``` interface implementation for POGOs. Is there any way to circumvent this error?

I prefer using Groovy for simple scripts, and norm is a great fit for them. Norm works great for me in Java but I need to set up a whole project to use it in Java :disappointed: 

Thanks!

**Comment by dieselpoint** [comment]
I don't have Groovy set up, so it's tough to test this solution:

Can you explicitly declare metaClass as a property, and then mark it
@Transient?

Does the metaClass have any other indicator on it that we can use to filter
it out?

The code that we use to extract properties is in
com.dieselpoint.norm.sqlmakers.StandardPojoInfo.java. You might spot
something there.


On Tue, Oct 27, 2015 at 1:04 PM, Jean Carlo <notifications@github.com>
wrote:

> First of all, great library. Small, easy to understand and use. Thanks for
> working on it.
>
> I'm trying to run the next Groovy script using norm (note that I've ran
> successfully the "same" code on a Java project):
>
> @GrabConfig(systemClassLoader=true)@Grab(group='mysql', module='mysql-connector-java', version='5.1.37')@Grab('org.eclipse.persistence:javax.persistence:2.1.0')@Grab('com.dieselpoint:norm:0.8.1-rc2')
> import com.dieselpoint.norm.Database;import com.dieselpoint.norm.Query;import com.dieselpoint.norm.sqlmakers.MySqlMaker;
> import java.util.List;import javax.persistence.*;
> @Table(name="data")class Data {
>   @Id
>   @GeneratedValue
>   long id;
>   String name;
>   long value;
>
>   public Data() {
>     this.id = 0;
>     this.name = "";
>     this.value = 0;
>   }
> }
> System.setProperty("norm.dataSourceClassName", "com.mysql.jdbc.jdbc2.optional.MysqlDataSource");System.setProperty("norm.serverName", "localhost");System.setProperty("norm.databaseName", "mytablename");System.setProperty("norm.user", "root");System.setProperty("norm.password", "s0meD1ficultPassw0rd");
> Database db = new Database();
> db.setSqlMaker(new MySqlMaker());
> List<Data> data = db.where("name=?", "SayMyName").results(Data.class);for(Data p : data) {
>   System.out.println(p.id + ": " + p.name + " => " + p.value);
>   System.out.println("****");
> }
>
> When I try to run it from the command line, the next error occurs:
>
> Caught: com.dieselpoint.norm.DbException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'metaClass' in 'field list'
> com.dieselpoint.norm.DbException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'metaClass' in 'field list'
>         at com.dieselpoint.norm.Query.results(Query.java:215)
>         at com.dieselpoint.norm.Query$results.call(Unknown Source)
>         at test-norm-groovy-error.run(test-norm-groovy-error.groovy:37)
> Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'metaClass' in 'field list'
>         at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
>         at com.mysql.jdbc.Util.getInstance(Util.java:387)
>         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
>         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
>         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
>         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
>         at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
>         at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
>         at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:52)
>         at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeQuery(HikariPreparedStatementProxy.java)
>         at com.dieselpoint.norm.Query.results(Query.java:186)
>         ... 2 more
>
> This is due to Groovy's metaclass interface implementation for POGOs. Is
> there any way to circumvent this error?
>
> I prefer using Groovy for simple scripts, and norm is a great fit for
> them. Norm works great for me in Java but I need to set up a whole project
> to use it in Java [image: :disappointed:]
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dieselpoint/norm/issues/10>.
>



-- 
Chris Cleveland
Dieselpoint, Inc.
http://dieselpoint.com
312-339-2677 mobile

**Comment by jeancarlozapata** [comment]
You are correct, I added the next code to class Data to mark ```metaClass``` as ```@Transient```:

```groovy
@Table(name="data")
class Data {
  // class fields and javax.persistence annotations...

  @Transient
  MetaClass getMetaClass()
  {
    return this.metaClass
  }
  // more stuff...
}
```
and the code now works correctly.

I'll try to take a look at ```com.dieselpoint.norm.sqlmakers.StandardPojoInfo.java``` later today (or maybe over the weekend) to try to find something that could be useful to not have to "hack" Groovy POGOs like that.

I'll close the issue, and, if I can do anything else, will open a pull request. 

Thanks for the fast response and your help!
