### ISSUE TITLE
exception by db.sql with '?' args

### ISSUE THREAD

**Issue by GreatFireWall** [dieselpoint/norm#13]
I want to check table exists to decide create it or not.
```
boolean exists = db.sql("select * from ? where type = table and name = ?",
                        "sqlite_master", tableName).first(Object.class) != null;
```
but throw exception
```
com.dieselpoint.norm.DbException: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (near "?": syntax error)
        at com.dieselpoint.norm.Query.execute(Query.java:344) ~[?:?]
```

Is it a bug?
By the way, is there any other ways to check table exists?

**Comment by ccleve** [comment]
You can't generally parameterize table names. See https://www.google.com/#q=parameterized+table+name You can assemble a string that does the same thing.

I'd check to see if there is some sqlite-specific code to check for existence of a table.
