### ISSUE TITLE
Error with renamed columns

### ISSUE THREAD

**Issue by Tsunamii** [dieselpoint/norm#17]
results() and resultsMap() always try to use the original column name

fix:
Query.java
line 137 & 204:
change meta.getColumnName(i); to meta.getColumnLabel(i);

more info here:
https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSetMetaData.html#getColumnLabel(int)

**Comment by ccleve** [comment]
Will check in the change shortly. Will you test it?

**Comment by Tsunamii** [comment]
thanks :) 
it's already tested locally and works like a charm :)
