### ISSUE TITLE
java.util.date not supported

### ISSUE THREAD

**Issue by semrick** [dieselpoint/norm#18]
This is a _nice_ utility! 

One small bug - Java date fields are converted to VARCHAR(255) fields in the database. Should really be DATETIME. Just needs another else clause in StandardSQLMaker getColType, like this:

} else if (dataType.equals(BigDecimal.class)) {
    colType = "decimal(" + precision + "," + scale + ")";
} **else if (dataType.equals(java.util.Date.class)) {
   colType = "datetime";
}** else {
  colType = "varchar(" + length + ")";
}

**Comment by ccleve** [comment]
Done and checked in. Will you test it?

**Comment by semrick** [comment]
Looks good. Thank you.
