### ISSUE TITLE
@Column is not working

### ISSUE THREAD

**Issue by drabiter** [dieselpoint/norm#2]
If I get it right, `PojoInfo` doesn't check the `@Column`. It only looks for `@Id` and `@GeneratedValue`.

**Comment by ccleve** [comment]
It's in the current snapshot version on master, but not on maven central. So the readme is out of sync with the latest released version. It'll be out soon.

**Comment by ccleve** [comment]
Version 0.8.1-rc1 should be on Maven Central shortly. Let me know if @Column works and I'll close this ticket.

**Comment by drabiter** [comment]
Confirmed works.
