### ISSUE TITLE
Hikari connection leak with NORM transaction?

### ISSUE THREAD

**Issue by JosRoseboom** [dieselpoint/norm#29]
Hi,
I regularly run into a connection leak on a transaction in a production system, but cannot reproduce this. Are there any known issues that cause a connection that norm gets from the pool for a transaction not to be returned (e.g. deadlocks)? 

`java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-2.7.8.jar!/:na]
	at com.dieselpoint.norm.Database.getConnection(Database.java:108) ~[norm-0.8.1.jar!/:na]
	at com.dieselpoint.norm.Database.startTransaction(Database.java:193) ~[norm-0.8.1.jar!/:na]
	at mypackage.MyClass.myMethod(MyClass.java:82) ~[classes!/:1.0-SNAPSHOT]`

**Comment by ccleve** [comment]
I'm not aware of an issue. It's shouldn't be possible; so far as I know, every call to getConnection() gets closed. In results() I wrap everything in a try/finally. Same thing with transation.commit or rollback.

A few ideas:
Can you stick in some logging code so we can see where connections are getting allocated but not released?
Are you always calling transaction.commit() or .rollback() when you're done with it?
Are there any exceptions getting logged? No exceptions getting suppressed?
Do these links help?
https://stackoverflow.com/questions/33887002/how-do-i-mitigate-connection-leak-triggered-for-connection-com-mysql-jdbc-jdbc4c
https://github.com/brettwooldridge/HikariCP/issues/923
https://github.com/brettwooldridge/HikariCP/issues/612
https://github.com/brettwooldridge/HikariCP/issues/1106

**Comment by JosRoseboom** [comment]
Thanks for the fast reply.

> Can you stick in some logging code so we can see where connections are getting allocated but not released?

Do you mean you want more code than the fragment that I submitted? Or should I add logging statements?

> Are you always calling transaction.commit() or .rollback() when you're done with it?

Yes. First line after startTransaction is try{ which has last line commit(). The catch has the rollback.

> Are there any exceptions getting logged? No exceptions getting suppressed?

No. Only exception is the apparent connection leak. Only try catch is after startTransaction.  

> Do these links help?

Yes. First thing to investigate for my is the cpu when the connection leak occurs. I assume same could happen when  the system runs out of ram. I will reply to this issue if either this was the cause or I can be sure this is not the cause.

Extra info: the os is windows server 2008, db is sql server 2008 R2.

**Comment by ccleve** [comment]
I meant, add logging statements to your code, if the other possible solutions in the links don't work out.

**Comment by JosRoseboom** [comment]
Finally figured out that there was a deadlock in the query. Because of this the connection was not given back.
