### ISSUE TITLE
Problem with RETURN_GENERATED_KEYS for all INSERTs 

### ISSUE THREAD

**Issue by sgsfak** [dieselpoint/norm#31]
The following example fails with exception: "The database table has an autogenerated key, but the pojo doesn't have a field with a @GeneratedValue annotation." The problem appears to be that norm creates a PreparedStatement with RETURN_GENERATED_KEYS for all INSERT statements (see [line 323 at Query.java](https://github.com/dieselpoint/norm/blob/48384388402e26e77ddbe99040f0d1518b8bc3e4/src/main/java/com/dieselpoint/norm/Query.java#L313)), irrespective whether the pojo has an auto-generated field or not. And by the way the [bug](http://www.postgresql.org/message-id/4BD196B4.3040607@smilehouse.com) referenced in the comment appears to have been fixed in the Postgres driver. 

Example:
```
import com.dieselpoint.norm.Database;
import javax.persistence.Column;
import javax.persistence.Table;

public class TestPG {
    @Table(name="test")
    public static class test {
        @Column
        public String t;
    };

    public static void main(String[] args) {
        Database db = new Database();
        db.setJdbcUrl("jdbc:postgresql://localhost:5432/testdb");
        db.setUser("me");
        db.setPassword("");

//        db.createTable(test.class);

        test v = new test();
        v.t="foo";
        db.insert(v).execute();
    }
}
```

**Comment by ccleve** [comment]
I'm thinking that if the pojo doesn't have @GenerateValue, then we just ignore it and don't throw the error. Sound reasonable?

**Comment by sgsfak** [comment]
Yes, I suppose it should work, thank you

**Comment by ccleve** [comment]
I've done a general rewrite of generated key handling. It's in the master branch. Have a look.
