### ISSUE TITLE
New StandardSqlMaker

### ISSUE THREAD

**Issue by ZZerog** [dieselpoint/norm#36]
Hi.

How subclass StandardSqlMaker when StandardPojoInfo have package private class members as table field?

I know is possible implement own StandardPojoInfo but why?

**Comment by ccleve** [comment]
Good point. Yes, this looks like a design error.

I can fix it in one of two ways: either make all the members public, or add getters and setters. The first way is cleaner, the second is more standard. I'll probably do it the first way.

For now, the workaround is to create your StandardSqlMaker class in the com.dieselpoint.norm.sqlmakers package. It's not ideal, but it will work.

**Comment by ccleve** [comment]
Change made and pushed to master. It will be in the next release.

**Comment by ccleve** [comment]
Oops, looks like I made too much public. I need to make insertSql and updateSql dynamic and need to take them out of StandardPojoInfo. Fortunately, that change didn't make it into a release. Reverting.
