### ISSUE TITLE
Compilation problem with HikariCP

### ISSUE THREAD

**Issue by drabiter** [dieselpoint/norm#4]
According to the `pom.xml`, the version of HikariCP is for Java 8 but Norm limits the compilation to 1.7 thus raising `Unsupported major.minor version 52.0`. I think the correct artifact is `HikariCP-java6`.

**Comment by ccleve** [comment]
You are correct. I've been using Java 8 to compile, even though the pom says 1.7. It works ok, but we should be consistent. Java 8 has been out for a year. What do you think, is it ok to require it?

**Comment by drabiter** [comment]
IMO it's okay. I have also set 8 as my primary.

**Comment by ccleve** [comment]
Have just pushed a change to the POM that requires jdk 1.8
