### ISSUE TITLE
Unable to handle DB exceptions

### ISSUE THREAD

**Issue by harishyadav-t** [dieselpoint/norm#45]

**Comment by harishyadav-t** [comment]
There is only one DbException for generic db exceptions.But what if I want to write custom messages for particular SQLIntegrityConstraintViolationException exception because DbExcpetion is generic.

 How to know whether it's SQLIntegrityConstraintViolationException or some other dbconnection exceptions or some other.

Please help me....

**Comment by ccleve** [comment]
Trap the DbException and examine exception.getCause(). That will give you the underlying exception.
