### ISSUE TITLE
Primitives

### ISSUE THREAD

**Issue by ZZerog** [dieselpoint/norm#46]
`Long count = db.sql("select count(*) from people").results(Long.class);`

Error:(79, 71) java: incompatible types: no instance(s) of type variable(s) T exist so that java.util.List<T> conforms to java.lang.Long

Typo? results instead first ?

**Comment by ccleve** [comment]
.results() returns a List. So, List<Long>. You're probably looking for .first() instead.

Long count = db.sql("select count(*) from people").first(Long.class);

**Comment by ccleve** [comment]
Documentation fixed. Thanks for catching that.
