### ISSUE TITLE
How to get row id after an insert ?

### ISSUE THREAD

**Issue by fhebuterne** [dieselpoint/norm#51]
Hi,

I search to retrieve row id after an insert with : **db.insert(entity);** but i don't find any method to do this, do you have a solution, please ?

Sincerely,
Fabien

**Comment by ccleve** [comment]
Make sure you have @Id and @GeneratedValue on your row id field in your entity. It should be filled in after insert() returns.

**Comment by fhebuterne** [comment]
It doesn't work, i have Id and GeneratedValue annotation on my id field but entity id is not filled after return

My example code : https://pastebin.com/Fgee5WPD

I'm using Lombok to generate getter and setter.

**Comment by fhebuterne** [comment]
Sorry i reopened issue because it work only when id is public but i want to restrict id in private and only put getter and setter in public with Lombok.

**Comment by ccleve** [comment]
Norm needs to see a public field or a public getter/setter. It searches for these things using class.getFields() for fields and Introspector.getBeanInfo().getPropertyDescriptors(). These use reflection internally. I'm not sure how Lombok generates getters and setters, but if they're not discoverable using reflection then Norm won't be able to use them.
