### ISSUE TITLE
In PostgreSQL @GeneratedValue causes Exception

### ISSUE THREAD

**Issue by tehnokraat** [dieselpoint/norm#7]
In PostgreSQL inserting the object below throws exception (org.postgresql.util.PSQLException: Bad value for type long).
@Table(name="customer")
public class Customer {
	@Id
	@GeneratedValue 
	public long id;
	public String name;
}

Please read this: http://stackoverflow.com/questions/19766816/postgresql-jdbc-getgeneratedkeys-returns-all-columns

I suggest 2 simple changes in method StandardPojoInfo.populateGeneratedKey:
1) newKey = generatedKeys.getInt(1) -> newKey = generatedKeys.getInt(generatedColumnName)
2) newKey = generatedKeys.getLong(1) -> newKey = generatedKeys.getLong(generatedColumnName)

**Comment by dieselpoint** [comment]
Just tried it with MySQL. The column name in the generatedKeys result set
is "GENERATED_KEY", so it doesn't work. Will need to find a different
solution. Might have to move the populateGeneratedKey() method into
SqlMaker class so we can have different code for different flavors of SQL.
Will do in the next day or two.

On Sun, Sep 20, 2015 at 4:23 AM, tehnokraat <notifications@github.com>
wrote:

> In PostgreSQL inserting the object below throws exception
> (org.postgresql.util.PSQLException: Bad value for type long).
> @Table <https://github.com/Table>(name="customer")
> public class Customer {
> @Id <https://github.com/Id>
> @GeneratedValue
> public long id;
> public String name;
> }
>
> Please read this:
> http://stackoverflow.com/questions/19766816/postgresql-jdbc-getgeneratedkeys-returns-all-columns
>
> I suggest 2 simple changes in method StandardPojoInfo.populateGeneratedKey:
> 1) newKey = generatedKeys.getInt(1) -> newKey =
> generatedKeys.getInt(generatedColumnName)
> 2) newKey = generatedKeys.getLong(1) -> newKey =
> generatedKeys.getLong(generatedColumnName)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dieselpoint/norm/issues/7>.
>



-- 
Chris Cleveland
Dieselpoint, Inc.
http://dieselpoint.com
312-339-2677 mobile

**Comment by ccleve** [comment]
Had to do a bunch of refactoring to make this work, but I just pushed the changes. I made it so populateGeneratedKeys() is now specific to a SQL flavor. I also fixed some postgres-specific problems with autoincrement fields and dealing with the fact that postgres always lowercases its column names. See notes in the readme. Will put a new version up on maven central shortly.
