### ISSUE TITLE
Multiple @Id, or Composite Primary Keys

### ISSUE THREAD

**Issue by TheTurkeyDev** [dieselpoint/norm#77]
Does this support composite keys, or using multiple @Id annotations? Currently running into an issue around this and was wondering if there's any other solution beyond falling back to raw sql. If there isn't an existing way, is this something that could be added?

**Comment by ccleve** [comment]
It doesn't look like I implemented composite primary keys using @id. You might be able to do it using getters and setters. Create a getter/setter for the id, annotate it, and internally split/gather the id into two fields. Haven't tried it, though.

Honestly, I've been dropping into straight SQL more and more in my apps. Sometimes it's best to have the ORM do less.

Could composite keys be added? Maybe, but I don't think the complexity is worth it if the getter/setter scheme works.

**Comment by ccleve** [comment]
I was thinking two key columns that become one value in code, but on
reflection that doesn't make any sense. The system wouldn't translate that
into SQL properly.
