### ISSUE TITLE
Use jakarta.persistence-api instead of javax.persistence-api

### ISSUE THREAD

**Issue by BITSchmid** [dieselpoint/norm#88]
**Feature request:**

With Spring Boot 3.x and other libraries "javax.persistence-api" is more and more outdated.
It would be great if a new major version could be released which uses jakarta.persistence-api.

**Comment by ccleve** [comment]
I accepted the change. I'm making a couple of other changes and then I'll do a release.

**Comment by BITSchmid** [comment]
Ok, perfect. Thx

**Comment by BITSchmid** [comment]
> I accepted the change. I'm making a couple of other changes and then I'll do a release.

Hi Chris. Do you already know when you will build the release? Thx

**Comment by ccleve** [comment]
1.2 done, sent to Maven Central. It always takes a while for them to publish. Should be there later today.

My plan was to change the way we do testing, but that will have to wait for the next release.
